[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "fraudstruct"
version = "1.0.0"
description = "Adversarial machine learning framework for bank fraud detection and model simulation"
readme = "README.md"
requires-python = ">=3.9"
license = {text = "MIT"}
authors = [
    {name = "Chidiebere V. Christopher", email = "vchidiebere.vc@gmail.com"}
]
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
    "Topic :: Security",
    "Topic :: Scientific/Engineering :: Artificial Intelligence"
]
dependencies = [
    "pandas>=1.5",
    "numpy>=1.23",
    "scikit-learn>=1.2",
    "fastapi>=0.95.0",
    "uvicorn>=0.20.0",
    "networkx>=2.8"
]

[project.urls]
"Homepage" = "https://github.com/93Chidiebere/Fraudstruct-Library"
"Repository" = "https://github.com/93Chidiebere/Fraudstruct-Library"

[project.optional-dependencies]
spark = ["pyspark>=3.4"]
dev = ["pytest", "black", "flake8", "jupyter", "build", "twine"]

